platform :ios, '7.0'

pod 'NSObjectExtend',               '~> 1.5.0' # NS系列类添加常用方法

pod 'AFNetworking',                 '~> 2.6.0' # Http网络请求
pod 'SVProgressHUD',                '~> 1.1.0' # 等待指示

pod 'APNumberPad',                  '~> 1.1.0' # 数字键盘
pod 'IQKeyboardManager',            '~> 3.2.0' # 防止键盘挡住输入框, 引入项目即可生效

pod 'ReactiveCocoa',                '~> 2.5.0' # 响应式编程框架
pod 'BlocksKit',                    '~> 2.2.0' # The Objective-C block utilities you always wish you had.
